version: "1"
rules:
  - base: main
    upstream: siamjuit/look-who-committed:main
    mergeMethod: hardreset  # Force sync - discards any local changes
    autoMerge: true
    autoMergeHardReset: true
